/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallasProducto;

import controlador.Coordinador_ModuloProductos;
import dtos.ProductoDTO;
import enumerators.EstadoProductoDTO;
import enumerators.TipoProductoDTO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import notificaciones.TipoNotificacion;
import notificaciones.DlgNotificacion2;

/**
 * Clase del frame Productos.
 * 
 * Aquí están declarados todos los componentes del JFrame junto con el 
 * compartamiento según la acción/evento que se realice con los mismos. 
 * 
 * @author María José Valdez Iglesias - 262775
 */
public class FrmProductos2 extends javax.swing.JFrame {
    
    /**
     * Atributo que representa el coordinador de las interfaces que representan
     * al módulo de los productos.
     */
    private Coordinador_ModuloProductos coordinador;
    
    /**
     * Sirve para guardar si los métodos de la BO dan verdadero/falso y saber 
     * cómo trabajar en base a ello.
     */
    private boolean resultado = false;
    
    /**
     * Logger para mandar mensajes de las operaciones.
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProductos2.class.getName());

    /**
     * Constructor del frame, donde establece el coordinador del frame y prepara
     * su vista.
     */
    public FrmProductos2(Coordinador_ModuloProductos coordinador) {
        this.coordinador = coordinador;
        initComponents();
        tipoBusqueda.setModel(new DefaultComboBoxModel<>(TipoProductoDTO.values()));
        tipoBusqueda.addItem(null);
        tblProductos.setFillsViewportHeight(true);
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        iconSistema = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnRepCom = new javax.swing.JButton();
        btnRepCli = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblBuscarpOR = new javax.swing.JPanel();
        lblProReg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        iconBusqueda = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        tipoBusqueda = new javax.swing.JComboBox<>();
        lblBuscarPor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1029, 627));

        jPanel1.setBackground(new java.awt.Color(255, 191, 71));
        jPanel1.setPreferredSize(new java.awt.Dimension(302, 80));

        lblProductos.setFont(new java.awt.Font("Trebuchet MS", 1, 42)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setText("Productos");

        iconSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_pequeño.png"))); // NOI18N
        iconSistema.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(iconSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconSistema))
        );

        jPanel2.setBackground(new java.awt.Color(255, 246, 222));
        jPanel2.setPreferredSize(new java.awt.Dimension(149, 356));

        btnClientes.setBackground(new java.awt.Color(255, 246, 222));
        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setFocusPainted(false);
        btnClientes.setPreferredSize(new java.awt.Dimension(78, 27));
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnProductos.setBackground(new java.awt.Color(255, 226, 150));
        btnProductos.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.setFocusPainted(false);
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnInventario.setBackground(new java.awt.Color(255, 246, 222));
        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.setFocusPainted(false);
        btnInventario.addActionListener(this::btnInventarioActionPerformed);

        btnReportes.setBackground(new java.awt.Color(255, 246, 222));
        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setFocusPainted(false);
        btnReportes.addActionListener(this::btnReportesActionPerformed);

        btnRepCom.setBackground(new java.awt.Color(255, 246, 222));
        btnRepCom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRepCom.setText("• Comandas");
        btnRepCom.setBorder(null);
        btnRepCom.setFocusPainted(false);

        btnRepCli.setBackground(new java.awt.Color(255, 246, 222));
        btnRepCli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRepCli.setText("• Clientes");
        btnRepCli.setBorder(null);
        btnRepCli.setFocusPainted(false);
        btnRepCli.addActionListener(this::btnRepCliActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRepCom)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRepCli, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRepCom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRepCli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBuscarpOR.setBackground(new java.awt.Color(255, 255, 255));
        lblBuscarpOR.setPreferredSize(new java.awt.Dimension(827, 541));

        lblProReg.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProReg.setText("Productos Registrados");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Tipo", "Descripción", "Precio", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        iconBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon buscar 32 kawaii.png"))); // NOI18N
        iconBusqueda.setText("jLabel4");

        btnAtras.setBackground(new java.awt.Color(47, 47, 47));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.setBorderPainted(false);
        btnAtras.setFocusPainted(false);
        btnAtras.setOpaque(true);
        btnAtras.addActionListener(this::btnAtrasActionPerformed);

        btnActivar.setBackground(new java.awt.Color(0, 153, 102));
        btnActivar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnActivar.setForeground(new java.awt.Color(255, 255, 255));
        btnActivar.setText("Activar");
        btnActivar.setBorderPainted(false);
        btnActivar.setFocusPainted(false);
        btnActivar.setOpaque(true);
        btnActivar.addActionListener(this::btnActivarActionPerformed);

        btnModificar.setBackground(new java.awt.Color(9, 94, 178));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorderPainted(false);
        btnModificar.setFocusPainted(false);
        btnModificar.setOpaque(true);
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnDesactivar.setBackground(new java.awt.Color(163, 0, 0));
        btnDesactivar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDesactivar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesactivar.setText("Desactivar");
        btnDesactivar.setBorderPainted(false);
        btnDesactivar.setFocusPainted(false);
        btnDesactivar.setOpaque(true);
        btnDesactivar.addActionListener(this::btnDesactivarActionPerformed);

        btnAgregar.setBackground(new java.awt.Color(181, 245, 255));
        btnAgregar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        btnAgregar.setText("+ Añadir Producto");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setFocusPainted(false);
        btnAgregar.setOpaque(true);
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tipoBusqueda.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        tipoBusqueda.addItemListener(this::tipoBusquedaItemStateChanged);

        lblBuscarPor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBuscarPor.setText("Buscar Por:");

        javax.swing.GroupLayout lblBuscarpORLayout = new javax.swing.GroupLayout(lblBuscarpOR);
        lblBuscarpOR.setLayout(lblBuscarpORLayout);
        lblBuscarpORLayout.setHorizontalGroup(
            lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBuscarpORLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(lblProReg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBuscarPor))
                        .addGap(18, 18, 18)
                        .addComponent(iconBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(33, 33, 33))
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesactivar)
                        .addGap(36, 36, 36))))
        );
        lblBuscarpORLayout.setVerticalGroup(
            lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblBuscarpORLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addComponent(lblProReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconBusqueda)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addComponent(lblBuscarPor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblBuscarpORLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblBuscarpORLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(lblBuscarpORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblBuscarpOR, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addComponent(lblBuscarpOR, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón que abre el módulo de clientes.
     */
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Aún no te puedo mandar para allá.");
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * Botón que abre el módulo de prductos.
     */
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Ya está en la opción de Productos.");
    }//GEN-LAST:event_btnProductosActionPerformed

    /**
     * Botón que abre el módulo de reportes.
     */
    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Aún no está disponible");
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * Botón que abre el módulo reportes - clientes.
     */
    private void btnRepCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepCliActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Aún no está disponible.");
    }//GEN-LAST:event_btnRepCliActionPerformed

    /**
     * Botón que abre el módulo de inventario-ingredientes.
     */
    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Aún no te puedo mandar para allá.");
    }//GEN-LAST:event_btnInventarioActionPerformed

    /**
     * Botón para regresar al panel de inicio del sistema.
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Aún no te puedo mandar para allá.");
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * Acción del botón activar.
     * 
     * Cuando un usuario desde activar un producto de la tabla, usa este botón 
     * para realizarlo.
     */
    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        int fila = tblProductos.getSelectedRow();        
        if(fila == -1){
            DlgNotificacion2.mostrarNotificacion(this, "Por favor seleccione un producto para activar.", TipoNotificacion.MENSAJE);
            return;
        }        
        ProductoDTO producto = (ProductoDTO) tblProductos.getValueAt(fila, 0);
        if(producto == null){
            DlgNotificacion2.mostrarNotificacion(this, "Producto inválido para seleccionar.", TipoNotificacion.MENSAJE);
            return;
        }
        if(producto.getEstado() == EstadoProductoDTO.ACTIVO){
            DlgNotificacion2.mostrarNotificacion(this, "Este producto ya se encuentra activo.", TipoNotificacion.MENSAJE);
            return;
        }
        resultado = coordinador.activarProducto(producto.getId());
        if(resultado){
            DlgNotificacion2.mostrarNotificacion(this, "Producto activado correctamente.", TipoNotificacion.ÉXITO);
            cargarTabla();
            return;
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    /**
     * Botón para agregar un nuevo Producto.
     * 
     * Se encarga de llamar al método del coordinador que se se mueve a la otra
     * pantalla.
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        coordinador.abrirFrmAgregarProducto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * Acción que busca entre los registros gracias al buscador del frame, que 
     * se va actualizando de forma dinámica a cómo vaya ingresando datos el
     * usuario.
     */
    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    /**
     * Botón para modificar un Producto de la tabla.
     * 
     * Se encarga de validar el producto seleccionado y llamar al método del
     * coordinador que viaja a la siguiente pantalla.
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        int fila = tblProductos.getSelectedRow();
        
        if(fila == -1){
            DlgNotificacion2.mostrarNotificacion(this, "Por favor seleccione un producto para modificar.", TipoNotificacion.MENSAJE);
            return;
        }
        ProductoDTO producto = (ProductoDTO) tblProductos.getValueAt(fila, 0);
        if(producto == null){
            DlgNotificacion2.mostrarNotificacion(this, "Producto inválido para seleccionar.", TipoNotificacion.MENSAJE);
            return;
        }
        coordinador.abrirFrmModificarProducto(producto);
        this.dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * Acción del botón desactivar.
     * 
     * Cuando un usuario desde desactivar un producto de la tabla, usa este botón 
     * para realizarlo.
     */
    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
        int fila = tblProductos.getSelectedRow();
        
        if(fila == -1){
            DlgNotificacion2.mostrarNotificacion(this, "Por favor seleccione un producto para desactivar.", TipoNotificacion.MENSAJE);
            return;
        }
        
        ProductoDTO producto = (ProductoDTO) tblProductos.getValueAt(fila, 0);
        if(producto == null){
            DlgNotificacion2.mostrarNotificacion(this, "Producto inválido para seleccionar.", TipoNotificacion.MENSAJE);
            return;
        }
        if(producto.getEstado() == EstadoProductoDTO.INACTIVO){
            DlgNotificacion2.mostrarNotificacion(this, "Este producto ya se encuentra inactivo.", TipoNotificacion.MENSAJE);
            return;
        } 
        resultado = coordinador.desactivarProducto(producto.getId());
        if(resultado){
            DlgNotificacion2.mostrarNotificacion(this, "Producto desactivado correctamente.", TipoNotificacion.ÉXITO);
            cargarTabla();
            return;
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void tipoBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoBusquedaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            filtrar();
        }
    }//GEN-LAST:event_tipoBusquedaItemStateChanged

    /**
     * Método que consulta todos los registros y se encarga de mostrarlos
     * en la tabla.
     */
    public void cargarTabla() {
        List<ProductoDTO> lista = coordinador.consultarTodosLosProductos();
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0);

        for (ProductoDTO p : lista) {
            model.addRow(new Object[]{
                p,
                p.getNombre(),
                p.getTipo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getEstado()
            });
        }
    }
    
    /**
     * Método para cargar la tabla con los registros filtrados.
     * @param lista Lista de registros filtrados.
     */
    public void cargarTablaFiltrada(List<ProductoDTO> lista){
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setRowCount(0);

        for (ProductoDTO p : lista) {
            model.addRow(new Object[]{
                p,
                p.getNombre(),
                p.getTipo(),
                p.getDescripcion(),
                p.getPrecio(),
                p.getEstado()
            });
        }
    }
    
    /**
     * Método para que filtre la información entre los registros que existan en
     * la BD.
     */
    private void filtrar(){
        String busqueda = txtBusqueda.getText().trim();
        Object opcionSeleccionado = tipoBusqueda.getSelectedItem();
        TipoProductoDTO tipo = null;
        if(opcionSeleccionado instanceof TipoProductoDTO){
            tipo = (TipoProductoDTO) opcionSeleccionado;
        }
        List<ProductoDTO> lista = coordinador.buscarProductos(busqueda, tipo);
        cargarTablaFiltrada(lista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRepCli;
    private javax.swing.JButton btnRepCom;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel iconBusqueda;
    private javax.swing.JLabel iconSistema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JPanel lblBuscarpOR;
    private javax.swing.JLabel lblProReg;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JComboBox<enumerators.TipoProductoDTO> tipoBusqueda;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
