 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.moduloIngredientes;

import controlador.CoordinadorInterfaces;
import controlador.Coordinador_ModuloIngredientes;
import dtos.IngredienteDTO;
import dtos.IngredienteNuevoDTO;
import enumerators.UnidadDTO;
import excepciones.NegocioException;
import excepciones.PersistenciaException;
import java.awt.Image;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import validaciones.ValidadorCampos;

/**
 * Pantalla que permite agregar/actualizar los ingredientes previamente almacenados en la base de datos.
 * 
 * Tiene dos vistas:
 * Agregar ingrediente
 * Actualizar Ingrediente
 * 
 * @author Alejandra Leal Armenta, 262719
 */
public class FrmAgregarIngrediente extends javax.swing.JFrame {
    
    CoordinadorInterfaces coordinadorInterfaces = new CoordinadorInterfaces();
    private Coordinador_ModuloIngredientes coordinador;
    File archivoImagen;
    private boolean modoActualizar = false;
    private IngredienteDTO ingredienteOriginal;
    

    /**
     * Creates new form FrmIngredientes
     */
    public FrmAgregarIngrediente(Coordinador_ModuloIngredientes coordinador) {
        this.coordinador = coordinador;
        
        initComponents();
        cargarCBXUnidad();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPantalla = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtStockInicial = new javax.swing.JTextField();
        lblMedida = new javax.swing.JLabel();
        lblStockInicial1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblAgregarImagen = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSubirImagen = new javax.swing.JLabel();
        lblStockMinimo = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        cbxMedida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 220, 175));

        jPanel2.setBackground(new java.awt.Color(255, 191, 71));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_pequeño.png"))); // NOI18N

        lblPantalla.setFont(new java.awt.Font("Trebuchet MS", 1, 42)); // NOI18N
        lblPantalla.setForeground(new java.awt.Color(255, 255, 255));
        lblPantalla.setText("Agregar Ingrediente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblTitulo.setText("Ingrediente");

        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");

        txtStockInicial.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        txtStockInicial.setBorder(null);
        txtStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockInicialActionPerformed(evt);
            }
        });

        lblMedida.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblMedida.setText("Medida");

        lblStockInicial1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStockInicial1.setText("Stock Inicial");

        btnCancelar.setBackground(new java.awt.Color(47, 47, 47));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(47, 47, 47));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblAgregarImagen.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAgregarImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarImagen.setText("Imagen (Opcional)");

        btnSubirImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubirImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upload.png"))); // NOI18N
        btnSubirImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubirImagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(btnSubirImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSubirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        lblStockMinimo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblStockMinimo.setText("Stock Minimo");

        txtStockMinimo.setFont(new java.awt.Font("Trebuchet MS", 0, 15)); // NOI18N
        txtStockMinimo.setBorder(null);
        txtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMinimoActionPerformed(evt);
            }
        });

        cbxMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtStockInicial)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNombre)
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addComponent(jSeparator2))
                            .addComponent(lblStockInicial1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStockMinimo)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblStockMinimo, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMedida)
                                    .addComponent(cbxMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(222, 222, 222))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cbxMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStockInicial1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStockMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAgregarImagen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockInicialActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        String nombre = txtNombre.getText();
        String stock = txtStockInicial.getText();
        String stockBajo = txtStockMinimo.getText();
        
        if(ValidadorCampos.nombreVacio(nombre)){
            JOptionPane.showMessageDialog(this, "Nombre obligatorio");
            return;
        }
        
        if (!ValidadorCampos.nombreValido(nombre)) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras");
            return;
        }
        
        if(!ValidadorCampos.soloNumeros(stock)){
            JOptionPane.showMessageDialog(this, "El stock solo puede contener numeros");
            return;
        }
        
        if(!ValidadorCampos.soloNumeros(stockBajo)){
            JOptionPane.showMessageDialog(this, "El stock solo puede contener numeros");
            return;
        }
        
        Integer stockInt = Integer.valueOf(stock);
        Integer stockBajoInt = Integer.valueOf(stockBajo);
        
        if(stockInt < 0){
            JOptionPane.showMessageDialog(this, "El Stock debe ser positivo");
            return;
        }
        
        if(stockBajoInt < 0){
            JOptionPane.showMessageDialog(this, "El Stock debe ser positivo");
            return;
        }
        
        int confirmacion;

        if (!modoActualizar) {
            confirmacion = JOptionPane.showConfirmDialog( this, "¿Estás seguro de que deseas agregar este ingrediente?", "Confirmar registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );
        } else {
            confirmacion = JOptionPane.showConfirmDialog( this, "¿Estás seguro de que deseas actualizar este ingrediente?", "Confirmar registro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE );
        }

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        UnidadDTO unidad = (UnidadDTO) cbxMedida.getSelectedItem();

        String rutaImagen = null;
        if (archivoImagen != null) {
            rutaImagen = archivoImagen.getAbsolutePath();
        }

        try {

            if (modoActualizar) {
                ingredienteOriginal.setNombre(txtNombre.getText());
                ingredienteOriginal.setStockActual(stockInt);
                ingredienteOriginal.setStockMinimo(stockBajoInt);
                ingredienteOriginal.setUnidadMedida(unidad);

                if (archivoImagen != null) {
                    ingredienteOriginal.setUrlImagen(rutaImagen);
                }
                coordinador.actualizarIngrediente(ingredienteOriginal);
                JOptionPane.showMessageDialog(this, "Ingrediente actualizado correctamente.");
                coordinador.abrirFrmIngredientes();
                this.dispose();

            } else {
                try{
                    coordinador.agregarIngrediente( new IngredienteNuevoDTO(txtNombre.getText(), unidad, stockInt, stockBajoInt, rutaImagen) );
                    JOptionPane.showMessageDialog(this, "Ingrediente agregado correctamente.");
                    coordinador.abrirFrmIngredientes();
                    this.dispose();
                } catch (NegocioException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnSubirImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirImagenMouseClicked
        coordinador.fileChooser();
    }//GEN-LAST:event_btnSubirImagenMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if(!txtNombre.getText().isEmpty() || !txtStockInicial.getText().isEmpty()){
            int opcion = JOptionPane.showConfirmDialog(this, "Se perderan los datos registrados", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                txtNombre.setText("");
                txtStockInicial.setText("");
                txtStockMinimo.setText("");
                coordinador.abrirFrmIngredientes();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinimoActionPerformed

    private void cbxMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMedidaActionPerformed
    
    /**
     * Agrega la imagen al campo de imagen del frame.
     * 
     * Muestra la imagen en el campo donde se agrega la imagen, la obtiene del fileChooser (panel)
     * @param archivo 
     */
    public void setImagenOpcional(File archivo){
        if (archivo == null) return;
        
        this.archivoImagen = archivo;  
        
        ImageIcon icono = new ImageIcon(archivo.getAbsolutePath());

        Image imagenEscalada = icono.getImage().getScaledInstance(
                120,   // tamaño real visible
                120,
                java.awt.Image.SCALE_SMOOTH
        );

        btnSubirImagen.setIcon(new ImageIcon(imagenEscalada));
    }
    
    /**
     * Carga el comboBox con las opciones del enumerator
     */
    private void cargarCBXUnidad() {
        cbxMedida.setModel(new javax.swing.DefaultComboBoxModel<>(UnidadDTO.values()));
    }
    
    /**
     * Cambia la interfaz de la pantalla dependiendo de donde se esta llamando a la pantalla.
     * 
     * Esta pantalla tienes dos usos, el de ingredientes y el de productos. Esconde y/o muestra componentes dependiendo de
     * donde venga el flujo. Desde la administracion de los ingredientres se agregan botones por ejmeplo, de añadir ingredientes,
     * actualizar, eliminar, etc, mientras de desde los productos muestra un panel lateral para agregar ingredientes a productos.
     * @param ingrediente 
     */
    public void modoActualizar(IngredienteDTO ingrediente){
        this.modoActualizar = true;

        this.ingredienteOriginal = ingrediente;

        lblTitulo.setText("Actualizar Ingrediente");
        lblPantalla.setText("Actualizar Ingrediente");
        btnAgregar.setText("Actualizar");

        txtNombre.setText(ingrediente.getNombre());
        txtStockInicial.setText(String.valueOf(ingrediente.getStockActual()));
        txtStockMinimo.setText(String.valueOf(ingrediente.getStockMinimo()));
        cbxMedida.setSelectedItem(ingrediente.getUnidadMedida());

        if (ingrediente.getUrlImagen() != null) {
            ImageIcon icono = new ImageIcon(ingrediente.getUrlImagen());
            Image img = icono.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            btnSubirImagen.setIcon(new ImageIcon(img));
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel btnSubirImagen;
    private javax.swing.JComboBox<UnidadDTO> cbxMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblAgregarImagen;
    private javax.swing.JLabel lblMedida;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPantalla;
    private javax.swing.JLabel lblStockInicial1;
    private javax.swing.JLabel lblStockMinimo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStockInicial;
    private javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables

}
