/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.moduloIngredientes;

import controlador.CoordinadorInterfaces;
import controlador.Coordinador_ModuloIngredientes;
import dtos.IngredienteDTO;
import dtos.ProductoIngredienteDTO;
import enumerators.TipoMovimiento;
import enumerators.UnidadDTO;
import excepciones.NegocioException;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import notificaciones.TipoNotificacion;
import notificaciones.dlgNotificacion;

/**
 * Pantalla donde se muestran los ingredientes.
 * 
 * Tiene dos vistas:
 * Administracion de ingredientes: elimina, actualiza, agrega y muestra los ingredientes (ale)
 * Añadir a productos: Agrega ingredientes a los productos (majojojo)
 * @author Alejandra Leal Armenta, 262719
 */
public class FrmIngredientes extends javax.swing.JFrame {
    
    /**
     * majojo:
     * Quite el que se creara aquí mismo el coordinador por lo mismo que 
     * comentaba en setCoordinadorIngredientes
     */
    Coordinador_ModuloIngredientes coordinador;
    CoordinadorInterfaces interfaces = new CoordinadorInterfaces();
    /**
     * majojo:
     * Es la lista que se van pasando entre coordinadores y frms, para que
     * manejen la misma referencia y no se pierda.
     */
    private List<ProductoIngredienteDTO> listaIngredientes;
    private List<IngredienteDTO> seleccionados = new ArrayList<>();
    private boolean modoProducto = false;

    /**
     * Creates new form FrmIngredientes
     */
    public FrmIngredientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarCBXUnidad();
        //cargarTabla();
    }
    
    /**
     * majojo:
     * Hice este método porqué si no manejaban coordinadores diferentes y pues
     * perdia comunicación ya que andaba en otro rollo el frm, y fue aquí donde
     * puse el cargar tabla que había en el constructor.
     * @param coordinador 
     */
    public void setCoordinadorIngredientes(Coordinador_ModuloIngredientes coordinador){
        this.coordinador = coordinador;
        if(coordinador != null){
            cargarTabla();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnInventario = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnProductos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnReportesClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnReportesComandas = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnAnadirIngrediente = new javax.swing.JButton();
        btnRestarStock = new javax.swing.JButton();
        btnActualizarIngrediente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollMenuLateral = new javax.swing.JScrollPane();
        pnlSeleccion = new javax.swing.JPanel();
        btnAgregarStock = new javax.swing.JButton();
        lblResumen = new javax.swing.JLabel();
        lblIngredientes = new javax.swing.JLabel();
        btnAgregarIngredientes = new javax.swing.JButton();
        cbxUnidadMedida = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 191, 71));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_pequeño.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Trebuchet MS", 1, 42)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 246, 222));

        btnClientes.setBackground(new java.awt.Color(255, 246, 222));
        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(255, 226, 150));
        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(255, 246, 222));
        btnProductos.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnReportesClientes.setBackground(new java.awt.Color(255, 246, 222));
        btnReportesClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportesClientes.setText("• Clientes");
        btnReportesClientes.setBorder(null);
        btnReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesClientesActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 246, 222));
        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnReportesComandas.setBackground(new java.awt.Color(255, 246, 222));
        btnReportesComandas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportesComandas.setText("• Comandas");
        btnReportesComandas.setBorder(null);
        btnReportesComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesComandasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReportesComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnReportesComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ingredientes");

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Medida", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIngredientes.setGridColor(new java.awt.Color(255, 255, 255));
        tblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        btnAtras.setBackground(new java.awt.Color(47, 47, 47));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.setBorder(null);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAnadirIngrediente.setBackground(new java.awt.Color(181, 245, 255));
        btnAnadirIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAnadirIngrediente.setText("+Añadir Ingrediente");
        btnAnadirIngrediente.setToolTipText("");
        btnAnadirIngrediente.setBorder(null);
        btnAnadirIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirIngredienteMouseClicked(evt);
            }
        });
        btnAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirIngredienteActionPerformed(evt);
            }
        });

        btnRestarStock.setBackground(new java.awt.Color(163, 0, 0));
        btnRestarStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnRestarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnRestarStock.setText("Restar Stock");
        btnRestarStock.setBorder(null);
        btnRestarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestarStockMouseClicked(evt);
            }
        });
        btnRestarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarStockActionPerformed(evt);
            }
        });

        btnActualizarIngrediente.setBackground(new java.awt.Color(0, 110, 153));
        btnActualizarIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnActualizarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarIngrediente.setText("Actualizar");
        btnActualizarIngrediente.setBorder(null);
        btnActualizarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarIngredienteMouseClicked(evt);
            }
        });
        btnActualizarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarIngredienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Unidad");

        scrollMenuLateral.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        pnlSeleccion.setLayout(new javax.swing.BoxLayout(pnlSeleccion, javax.swing.BoxLayout.Y_AXIS));
        scrollMenuLateral.setViewportView(pnlSeleccion);

        btnAgregarStock.setBackground(new java.awt.Color(0, 153, 102));
        btnAgregarStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarStock.setText("Agregar Stock");
        btnAgregarStock.setBorder(null);
        btnAgregarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarStockMouseClicked(evt);
            }
        });
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });

        lblResumen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResumen.setText("Resumen");

        lblIngredientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIngredientes.setText("Ingredientes");

        btnAgregarIngredientes.setBackground(new java.awt.Color(0, 153, 102));
        btnAgregarIngredientes.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarIngredientes.setText("Agregar Ingredientes");
        btnAgregarIngredientes.setBorder(null);
        btnAgregarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIngredientesActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(185, 185, 185)
                                        .addComponent(lblTitulo))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(217, 217, 217)
                                        .addComponent(btnAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addComponent(lblResumen)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addComponent(lblIngredientes)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addComponent(btnAgregarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblResumen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIngredientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrollMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTitulo)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnAnadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxUnidadMedida)
                                            .addComponent(txtBusqueda))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnRestarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnActualizarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * majojo:
     * Es para que se pasen la misma referencia a la lista que se creó desde
     * el coordinador de productos.
     * @param lista 
     */
    public void setListaIngredientes(List<ProductoIngredienteDTO> lista){
        this.listaIngredientes = lista;
    }
    
    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesClientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportesComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesComandasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesComandasActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed

    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        String busqueda = txtBusqueda.getText().trim();

        TableRowSorter<DefaultTableModel> ordenador = new TableRowSorter(tblIngredientes.getModel());
        tblIngredientes.setRowSorter(ordenador);

        if(busqueda.isBlank() || busqueda.isEmpty() || busqueda.length() == 0){
            ordenador.setRowFilter(null);
        } else {
            /*
            el (?i) es para que busque sin importar mayúsculas y minúsculas.
            falta q busque sin importar acentos.
            */
            ordenador.setRowFilter(RowFilter.regexFilter("(?i)" + busqueda, 1, 2));
        }
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAnadirIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirIngredienteMouseClicked
        coordinador.abrirFrmAgregarIngrediente();
        this.dispose();
    }//GEN-LAST:event_btnAnadirIngredienteMouseClicked

    private void btnAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirIngredienteActionPerformed

    }//GEN-LAST:event_btnAnadirIngredienteActionPerformed

    private void btnRestarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestarStockMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();

        IngredienteDTO ingrediente = (IngredienteDTO) modelo.getValueAt(fila, 0);
        
        String nombre = modelo.getValueAt(fila, 1).toString();
        int stockActual = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
        
        coordinador.frmIngredientesADlgModificarStock(nombre, TipoMovimiento.SALIDA);
        
        Integer cantidad = coordinador.cantidadStock();
        
        try{
            if(cantidad != null){
                coordinador.actualizarStock(ingrediente.getId(), cantidad, TipoMovimiento.SALIDA);
            }
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnRestarStockMouseClicked

    private void btnRestarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestarStockActionPerformed

    private void btnActualizarIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarIngredienteMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();

        IngredienteDTO ingrediente = (IngredienteDTO) modelo.getValueAt(fila, 0);
        
        String nombre = modelo.getValueAt(fila, 1).toString();
        int stockActual = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
        
        coordinador.frmIngredientesAFrmActualizarIngrediente(ingrediente);
        this.dispose();
        cargarTabla();
        
    }//GEN-LAST:event_btnActualizarIngredienteMouseClicked

    private void btnActualizarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarIngredienteActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        interfaces.mostrarFormularioClientes();
        this.dispose();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void tblIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngredientesMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        IngredienteDTO ing = (IngredienteDTO) tblIngredientes.getValueAt(fila, 0);
        try{
            if (evt.getClickCount() == 2 && !modoProducto) {
                int opcion = JOptionPane.showConfirmDialog( this, "¿Deseas eliminar este ingrediente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION );

                if (opcion == JOptionPane.YES_OPTION) {
                    coordinador.eliminarIngrediente(ing);
                }
                cargarTabla();
                return;
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        

        if (modoProducto) {
            agregarIngrediente(ing);
        }
    }//GEN-LAST:event_tblIngredientesMouseClicked

    private void btnAgregarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarStockMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();

        IngredienteDTO ingrediente = (IngredienteDTO) modelo.getValueAt(fila, 0);
        
        String nombre = modelo.getValueAt(fila, 1).toString();
        int stockActual = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
        
        coordinador.frmIngredientesADlgModificarStock(nombre, TipoMovimiento.ENTRADA);
        
        Integer cantidad = coordinador.cantidadStock();
        
        try{
            if(cantidad != null){
                coordinador.actualizarStock(ingrediente.getId(), cantidad, TipoMovimiento.ENTRADA);
            }
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarStockMouseClicked

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnAgregarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredientesActionPerformed
        // TODO add your handling code here:
        // si es diferente de null la limpia para que no se quede con registros anteriores.
        if(listaIngredientes != null){
            listaIngredientes.clear();
            /*
            si de casualidad no existe la lista, la crea.
            */
        } else {
            listaIngredientes = new ArrayList<>();
        }
        /**
         * De los paneles que agregó, recupera los datos para crear el objeto
         * ProductoIngredienteDTO y guardarlo en la lista.
         */
        for(Component c : pnlSeleccion.getComponents()){
            if(c instanceof panIngredientesProducto p){
                listaIngredientes.add(new ProductoIngredienteDTO(p.getIngrediente(), p.getCantidad()));
            }
        }
        /**
         * Valida que si hayan agregado ingredientes y no quieran mandarlos vacíos.
         */
        if(listaIngredientes.isEmpty()){
            dlgNotificacion.mostrarNotificacion(this, "Por favor de seleccionar ingredientes para agregar al producto.", TipoNotificacion.MENSAJE);
            return;
        }
        
        /**
         * Pide confirmación.
         */
        int opcion = dlgNotificacion.mostrarNotificacion(this, "¿Seguro de agregar dichos ingredientes al producto?", TipoNotificacion.CONFIRMACIÓN);
        if(opcion == dlgNotificacion.RET_CANCELAR){
            return;
        }
        
        /**
         * Le pasa la lista al coordinador para que la pase al otro coordinador
         * y este se la pueda pasar al frmAgregarProducto.
         */
        coordinador.setListaIngredientes(this.listaIngredientes);
        /*
        Se regresa al frm de agregar prooducto.
        */
        coordinador.abrirFrmAgregarProducto();
        
    }//GEN-LAST:event_btnAgregarIngredientesActionPerformed
    
    /**
     * Actualiza la tabla donde se ven los ingredientes
     */
    public void cargarTabla(){
        try{
            DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();
            modelo.setRowCount(0);
            
            List<IngredienteDTO> lista = coordinador.obtenerIngredientes(); 
            
            for (IngredienteDTO ing : lista) {
                modelo.addRow(new Object[]{
                    ing,
                    ing.getNombre(),
                    ing.getUnidadMedida(),
                    ing.getStockActual()
                });
            }
        } catch (NegocioException ex){
            JOptionPane.showMessageDialog(this, "Error al cargar ingredientes: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Activa la vista desde el flujo de los productos. Donde se agregan ingredientes a productops
     */
    public void activarModoProducto(){
        modoProducto = true;
        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 427));

        scrollMenuLateral.setVisible(true);
        /**
         * majojo:
         * Le cambie el layout para que se viera kawaii porque si no se movía todo
         * bien raro.
         */
        pnlSeleccion.setLayout(new BoxLayout(pnlSeleccion, BoxLayout.Y_AXIS));
        pnlSeleccion.setVisible(true);

        /**
         * majojo:
         * Simplemente que se active el botón que agregué abajo de pnlSelección.
         */
        btnAgregarIngredientes.setVisible(true);
        lblResumen.setVisible(true);
        lblIngredientes.setVisible(true);
        btnActualizarIngrediente.setVisible(false);
        btnAgregarStock.setVisible(false);
        btnAnadirIngrediente.setVisible(false);
        btnRestarStock.setVisible(false);

        panPrincipal.revalidate();
        panPrincipal.repaint();

        this.pack();
    }
    
    /**
     * Muestra la vista desde el flujo de ingredientes. Donde se administran los ingredientes
     */
    public void desactivarModoProducto() {
        modoProducto = false;
        pnlSeleccion.removeAll();

        scrollMenuLateral.setVisible(false);
        btnAtras.setVisible(false);
        /*
        majojo:
        Misma, que se desactive el botón que agregué.
        */
        btnAgregarIngredientes.setVisible(false);
        lblResumen.setVisible(false);
        lblIngredientes.setVisible(false);

        panPrincipal.remove(scrollMenuLateral);
        panPrincipal.revalidate();
        panPrincipal.repaint();
        
        this.pack();
    }
    
    /**
     * majojo:
     * Por si en el panIngredienresProducto le dan click al botón de eliminar, 
     * usa este método para eliminar el panel de esta pantalla.
     * @param panel El panel que se quiere eliminar.
     */
    public void eliminarIngrediente(panIngredientesProducto panel){
        pnlSeleccion.remove(panel);
        pnlSeleccion.revalidate();
        pnlSeleccion.validate();
    }
    
    /**
     * Agrega los ingredientes mediante un formato para que al agregarlos al panel lateral
     * se vean bonitos y tengan sus debidas funcionalidades para la vista de productos.
     * @param ing 
     */
    private void agregarIngrediente(IngredienteDTO ing) {

        for (Component c : pnlSeleccion.getComponents()) {
            if (c instanceof panIngredientesProducto) {
                panIngredientesProducto p = (panIngredientesProducto) c;
                if (p.getNombre().equals(ing.getNombre())) {
                    p.incrementarCantidad();
                    return;
                }
            }
        }
        
        panIngredientesProducto item = new panIngredientesProducto();
        item.setFrmPadre(this);
        item.setIngrediente(ing);
        item.setNombre(ing.getNombre());
        item.setUnidad(ing.getUnidadMedida());
        item.setImagen(ing.getUrlImagen());
        item.setCantidad(1);
        /**
         * majojo:
         * Igual, para que se vean kawaii.
         */
        item.setMaximumSize(new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height));  
        item.setAlignmentX(Component.CENTER_ALIGNMENT);

        /**
         * majojo:
         * Como quedaba un espacio sin rellenar, este lo rellena.
         */
        for (Component c : pnlSeleccion.getComponents()) {
            if (c instanceof Box.Filler) {
                pnlSeleccion.remove(c);
            }
        }
        pnlSeleccion.add(item);
        /*
        majojo:
        Es para que no se amontonen los componentes, a lo que estuve leyendo.
        */
        pnlSeleccion.add(Box.createVerticalGlue());
        pnlSeleccion.revalidate();
        pnlSeleccion.repaint();
        
        /**
         * majojo:
         * Según yo esto es para que vayan apilandose de forma ascendente (o sea
         * el último agregado va hacía abajo), aunq no me creas tanto porque esto
         * sí se lo pregunté al geminicio.
         */
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JScrollBar vertical = scrollMenuLateral.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });
    }
    
    private void cargarCBXUnidad() {
        cbxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(UnidadDTO.values()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarIngrediente;
    private javax.swing.JButton btnAgregarIngredientes;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnAnadirIngrediente;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportesClientes;
    private javax.swing.JButton btnReportesComandas;
    private javax.swing.JButton btnRestarStock;
    private javax.swing.JComboBox<UnidadDTO> cbxUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel pnlSeleccion;
    private javax.swing.JScrollPane scrollMenuLateral;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
