/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.moduloIngredientes;

import controlador.CoordinadorInterfaces;
import controlador.Coordinador_ModuloIngredientes;
import dtos.IngredienteDTO;
import enumerators.TipoMovimiento;
import excepciones.NegocioException;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Home
 */
public class FrmIngredientes extends javax.swing.JFrame {
    
    Coordinador_ModuloIngredientes coordinador = new Coordinador_ModuloIngredientes();
    CoordinadorInterfaces interfaces = new CoordinadorInterfaces();
    
    private List<IngredienteDTO> seleccionados = new ArrayList<>();
    private boolean modoProducto = false;

    /**
     * Creates new form FrmIngredientes
     */
    public FrmIngredientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnInventario = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnProductos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnReportesClientes = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnReportesComandas = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        btnAnadirIngrediente = new javax.swing.JButton();
        btnRestarStock = new javax.swing.JButton();
        btnAgregarStock = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlSeleccion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 191, 71));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_blanco_pequeño.png"))); // NOI18N

        lblClientes.setFont(new java.awt.Font("Trebuchet MS", 1, 42)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 246, 222));

        btnClientes.setBackground(new java.awt.Color(255, 246, 222));
        btnClientes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(255, 226, 150));
        btnInventario.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setBorder(null);
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(255, 246, 222));
        btnProductos.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnReportesClientes.setBackground(new java.awt.Color(255, 246, 222));
        btnReportesClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportesClientes.setText("• Clientes");
        btnReportesClientes.setBorder(null);
        btnReportesClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesClientesActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(255, 246, 222));
        btnReportes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnReportesComandas.setBackground(new java.awt.Color(255, 246, 222));
        btnReportesComandas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReportesComandas.setText("• Comandas");
        btnReportesComandas.setBorder(null);
        btnReportesComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesComandasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReportesComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnReportesComandas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Ingredientes");

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Medida", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblIngredientes.setGridColor(new java.awt.Color(255, 255, 255));
        tblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        btnAtras.setBackground(new java.awt.Color(47, 47, 47));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.setBorder(null);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAnadirIngrediente.setBackground(new java.awt.Color(181, 245, 255));
        btnAnadirIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAnadirIngrediente.setText("+Añadir Ingrediente");
        btnAnadirIngrediente.setToolTipText("");
        btnAnadirIngrediente.setBorder(null);
        btnAnadirIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnadirIngredienteMouseClicked(evt);
            }
        });
        btnAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirIngredienteActionPerformed(evt);
            }
        });

        btnRestarStock.setBackground(new java.awt.Color(163, 0, 0));
        btnRestarStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnRestarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnRestarStock.setText("Restar Stock");
        btnRestarStock.setBorder(null);
        btnRestarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestarStockMouseClicked(evt);
            }
        });
        btnRestarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarStockActionPerformed(evt);
            }
        });

        btnAgregarStock.setBackground(new java.awt.Color(0, 153, 102));
        btnAgregarStock.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAgregarStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarStock.setText("Agregar Stock");
        btnAgregarStock.setBorder(null);
        btnAgregarStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarStockMouseClicked(evt);
            }
        });
        btnAgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarStockActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlSeleccion.setBackground(new java.awt.Color(204, 204, 204));
        pnlSeleccion.setLayout(new javax.swing.BoxLayout(pnlSeleccion, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(pnlSeleccion);

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(275, 275, 275)
                        .addComponent(lblTitulo))
                    .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panPrincipalLayout.createSequentialGroup()
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnRestarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panPrincipalLayout.createSequentialGroup()
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblTitulo))
                        .addGap(10, 10, 10)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRestarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnReportesClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesClientesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesClientesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportesComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesComandasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No disponible aún...");
    }//GEN-LAST:event_btnReportesComandasActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed

    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        String busqueda = txtBusqueda.getText().trim();

        TableRowSorter<DefaultTableModel> ordenador = new TableRowSorter(tblIngredientes.getModel());
        tblIngredientes.setRowSorter(ordenador);

        if(busqueda.isBlank() || busqueda.isEmpty() || busqueda.length() == 0){
            ordenador.setRowFilter(null);
        } else {
            /*
            el (?i) es para que busque sin importar mayúsculas y minúsculas.
            falta q busque sin importar acentos.
            */
            ordenador.setRowFilter(RowFilter.regexFilter("(?i)" + busqueda, 1, 2));
        }
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAnadirIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnadirIngredienteMouseClicked
        coordinador.abrirFrmAgregarIngrediente();
        this.dispose();
    }//GEN-LAST:event_btnAnadirIngredienteMouseClicked

    private void btnAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirIngredienteActionPerformed

    }//GEN-LAST:event_btnAnadirIngredienteActionPerformed

    private void btnRestarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestarStockMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();

        IngredienteDTO ingrediente = (IngredienteDTO) modelo.getValueAt(fila, 0);
        
        String nombre = modelo.getValueAt(fila, 1).toString();
        int stockActual = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
        
        coordinador.frmIngredientesADlgModificarStock(nombre, TipoMovimiento.SALIDA);
        
        Integer cantidad = coordinador.cantidadStock();
        
        try{
            if(cantidad != null){
                coordinador.actualizarStock(ingrediente.getId(), cantidad, TipoMovimiento.SALIDA);
            }
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnRestarStockMouseClicked

    private void btnRestarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestarStockActionPerformed

    private void btnAgregarStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarStockMouseClicked
        int fila = tblIngredientes.getSelectedRow();
        
        if(fila == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla", "Ingrediente no seleccionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();

        IngredienteDTO ingrediente = (IngredienteDTO) modelo.getValueAt(fila, 0);
        
        String nombre = modelo.getValueAt(fila, 1).toString();
        int stockActual = Integer.parseInt(modelo.getValueAt(fila, 3).toString());
        
        coordinador.frmIngredientesADlgModificarStock(nombre, TipoMovimiento.ENTRADA);
        
        Integer cantidad = coordinador.cantidadStock();
        
        try{
            if(cantidad != null){
                coordinador.actualizarStock(ingrediente.getId(), cantidad, TipoMovimiento.ENTRADA);
            }
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnAgregarStockMouseClicked

    private void btnAgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarStockActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        interfaces.mostrarFormularioClientes();
        this.dispose();
    }//GEN-LAST:event_btnClientesMouseClicked

    private void tblIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngredientesMouseClicked
        if (!modoProducto) return;

        int fila = tblIngredientes.getSelectedRow();
        if (fila == -1) return;

        IngredienteDTO ing = (IngredienteDTO) tblIngredientes.getValueAt(fila, 0);

        agregarIngrediente(ing);
    }//GEN-LAST:event_tblIngredientesMouseClicked
    
    public void cargarTabla(){
        try{
            DefaultTableModel modelo = (DefaultTableModel) tblIngredientes.getModel();
            modelo.setRowCount(0);
            
            List<IngredienteDTO> lista = coordinador.obtenerIngredientes(); 
            
            for (IngredienteDTO ing : lista) {
                modelo.addRow(new Object[]{
                    ing,
                    ing.getNombre(),
                    ing.getUnidadMedida(),
                    ing.getStock()
                });
            }
        } catch (NegocioException ex){
            JOptionPane.showMessageDialog(this, "Error al cargar ingredientes: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    public void activarModoProducto(){
        modoProducto = true;

        // 1. Regresar la tabla a su tamaño original para que quepa el panel
        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 427));
        jScrollPane1.setSize(new java.awt.Dimension(750, 427));

        // 2. Mostrar el panel de selección
        jScrollPane2.setVisible(true);
        pnlSeleccion.setVisible(true);

        btnAgregarStock.setVisible(false);
        btnAnadirIngrediente.setVisible(false);
        btnRestarStock.setVisible(false);

        panPrincipal.revalidate();
        panPrincipal.repaint();
    }
    
    public void desactivarModoProducto() {
        modoProducto = false;
        pnlSeleccion.removeAll();

        // 1. Ocultar el panel de la derecha
        jScrollPane2.setVisible(false);

        // 2. FORZAR a la tabla a expandirse
        // Vamos a sumar el ancho de la tabla + el ancho que tenía el panel de selección
        // (Ajusta el 750 y el 200 según tus medidas originales en NetBeans)
        jScrollPane1.setPreferredSize(new java.awt.Dimension(950, 427)); 
        jScrollPane1.setSize(new java.awt.Dimension(950, 427));

        // 3. Actualizar
        panPrincipal.revalidate();
        panPrincipal.repaint();
    }
    
    private void agregarIngrediente(IngredienteDTO ing) {

        for (Component   c : pnlSeleccion.getComponents()) {
            if (c instanceof panIngredientesProducto) {
                panIngredientesProducto p = (panIngredientesProducto) c;
                if (p.getNombre().equals(ing.getNombre())) {
                    p.incrementarCantidad(); // en vez de duplicar
                    return;
                }
            }
        }
        
        panIngredientesProducto item = new panIngredientesProducto();

        // aquí le pasas datos (IMPORTANTE)
        item.setNombre(ing.getNombre());
        item.setUnidad(ing.getUnidadMedida());
        item.setImagen(ing.getUrlImagen());
        item.setCantidad(1);

        pnlSeleccion.add(item);
        pnlSeleccion.revalidate();
        pnlSeleccion.repaint();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnAnadirIngrediente;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportesClientes;
    private javax.swing.JButton btnReportesComandas;
    private javax.swing.JButton btnRestarStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel pnlSeleccion;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
