package pantallas.moduloComandas.vistas;

import controlador.CoordinadorModuloComandas;
import dtos.ComandaDTO;
import dtos.DetalleComandaDTO;
import dtos.ProductoDTO;
import excepciones.NegocioException;

/**
 *
 * @author Brian Kaleb Sandoval Rodríguez - 00000262741
 */
public class frmResumen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmResumen.class.getName());
    private CoordinadorModuloComandas coordinador;

    /**
     * Creates new form frmRecibo
     *
     * @param comanda
     * @param coordinador
     */
    public frmResumen(ComandaDTO comanda, CoordinadorModuloComandas coordinador) {
        initComponents();
        this.coordinador = coordinador;
        txaResumen.setText(construirMensajeComanda(comanda));
        lblTotal.setText("Total: $" + comanda.getTotal() + " MXN");
    }

    /**
     * Construye el mensaje detallado de la comanda.
     *
     * @param comanda Comanda a mostrar
     * @return Texto formateado
     */
    private String construirMensajeComanda(ComandaDTO comanda) {
        StringBuilder mensaje = new StringBuilder();

        if (comanda.getCliente() != null) {
            mensaje.append("Cliente: ")
                    .append(comanda.getCliente().getNombres())
                    .append(" ")
                    .append(comanda.getCliente().getApellidoPaterno())
                    .append("\n\n");
        }

        mensaje.append("Detalles:\n");

        for (DetalleComandaDTO d : comanda.getDetalles()) {
            try {
                ProductoDTO producto = coordinador.obtenerProducto(d.getIdProducto());

                mensaje.append("- ")
                        .append(producto.getNombre())
                        .append(" x").append(d.getCantidad())
                        .append(" $").append(d.getPrecioUnitario());

                if (d.getComentario() != null && !d.getComentario().isBlank()) {
                    mensaje.append(" (").append(d.getComentario()).append(")");
                }

                mensaje.append("\n");

            } catch (NegocioException e) {
                mensaje.append("- Producto desconocido\n");
            }
        }

        return mensaje.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panContenedorComanda = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaResumen = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Resumen Comanda");

        panContenedorComanda.setBackground(new java.awt.Color(255, 255, 255));

        txaResumen.setBackground(new java.awt.Color(255, 255, 255));
        txaResumen.setColumns(20);
        txaResumen.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txaResumen.setRows(5);
        txaResumen.setEnabled(false);
        jScrollPane2.setViewportView(txaResumen);

        javax.swing.GroupLayout panContenedorComandaLayout = new javax.swing.GroupLayout(panContenedorComanda);
        panContenedorComanda.setLayout(panContenedorComandaLayout);
        panContenedorComandaLayout.setHorizontalGroup(
            panContenedorComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenedorComandaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panContenedorComandaLayout.setVerticalGroup(
            panContenedorComandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panContenedorComanda);

        jButton1.setBackground(new java.awt.Color(37, 201, 32));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lblTotal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panContenedorComanda;
    private javax.swing.JTextArea txaResumen;
    // End of variables declaration//GEN-END:variables
}
