package pantallas.moduloComandas.vistas;

import controlador.CoordinadorModuloComandas;
import dtos.ComandaDTO;
import dtos.DetalleComandaDTO;
import excepciones.NegocioException;
import java.util.List;
import javax.swing.BoxLayout;

/**
 *
 * @author Kaleb
 */
public class panPedidos extends javax.swing.JPanel {

    private final ComandaDTO comanda;
    private final CoordinadorModuloComandas coordinador;

    /**
     * Creates new form panPedido
     *
     * @param comanda
     * @param coordinador
     * @throws excepciones.NegocioException
     */
    public panPedidos(ComandaDTO comanda, CoordinadorModuloComandas coordinador) throws NegocioException {
        initComponents();
        this.comanda = comanda;
        this.coordinador = coordinador;

        this.setPreferredSize(jPanel1.getPreferredSize());
        this.setMaximumSize(jPanel1.getPreferredSize());

        panContenedor.setLayout(new BoxLayout(panContenedor, BoxLayout.Y_AXIS));
        panContenedor.removeAll();

        lblCliente.setText(comanda.getCliente().getNombres() + " " + comanda.getCliente().getApellidoPaterno());

        List<DetalleComandaDTO> detalles = comanda.getDetalles();

        for (DetalleComandaDTO detalle : detalles) {
            panProductoPedido producto = new panProductoPedido(detalle, coordinador);

            producto.setPreferredSize(new java.awt.Dimension(650, 50));
            producto.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));

            panContenedor.add(producto);
        }

        panContenedor.revalidate();
        panContenedor.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panContenedor = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblCliente.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("jLabel1");

        jScrollPane1.setBackground(new java.awt.Color(255, 241, 193));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panContenedor.setBackground(new java.awt.Color(255, 241, 193));

        javax.swing.GroupLayout panContenedorLayout = new javax.swing.GroupLayout(panContenedor);
        panContenedor.setLayout(panContenedorLayout);
        panContenedorLayout.setHorizontalGroup(
            panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        panContenedorLayout.setVerticalGroup(
            panContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panContenedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JPanel panContenedor;
    // End of variables declaration//GEN-END:variables
}
