package pantallas.moduloComandas.vistas;

import controlador.CoordinadorModuloComandas;
import dtos.ProductoDTO;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Kaleb
 */
public class panProductoMenu extends javax.swing.JPanel {

    private CoordinadorModuloComandas coordinador;

    private ProductoDTO producto;

    /**
     * Creates new form panProductoMenu
     *
     * @param producto
     */
    public panProductoMenu(ProductoDTO producto, CoordinadorModuloComandas coordinador) {
        initComponents();

        this.producto = producto;
        this.coordinador = coordinador;

        setPreferredSize(new java.awt.Dimension(140, 140));
        setMinimumSize(new java.awt.Dimension(140, 140));
        setMaximumSize(new java.awt.Dimension(140, 140));

        setLayout(new java.awt.BorderLayout());

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        add(lblImagen, java.awt.BorderLayout.CENTER);
        add(lblNombre, java.awt.BorderLayout.SOUTH);

        lblNombre.setText(producto.getNombre());

        if (producto.getUrlImagen() != null && !producto.getUrlImagen().isEmpty()) {
            java.net.URL url = getClass().getResource(producto.getUrlImagen());

            if (url != null) {
                ImageIcon icon = new ImageIcon(url);
                Image img = icon.getImage().getScaledInstance(140, 100, Image.SCALE_SMOOTH);
                lblImagen.setIcon(new ImageIcon(img));
                lblImagen.setText("");
            } else {
                lblImagen.setText("No img");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setText("jLabel1");

        lblNombre.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        coordinador.agregarProductoInterfaz(producto);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
