/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package notificaciones;

import java.awt.Frame;
import java.util.logging.Logger;
import javax.swing.JDialog;

/**
 * Clase JDialog para mostrar notificaciones con un diseño personalizado que 
 * asemeja al diseño del resto del sistema.
 * 
 * @author María José Valdez Iglesias - 262775
 */
public class dlgNotificacion extends JDialog {
   
    /**
     * Logger de la clase para notificar resultados de las operaciones. 
     */
    private static final Logger logger = Logger.getLogger(dlgNotificacion.class.getName());

    /**
     * Opción que el usuario selecciona del JDialog.
     */
    private int opcion;
    
    /**
     * Variable estática que representa que el usuario canceló la operación.
     */
    public static final int RET_CANCELAR = 0;
    
    /**
     * Variable estática que representa que el usuario aceptó la operación.
     */
    public static final int RET_ACEPTAR = 1;

    /**
     * Constructor de la clase.
     * 
     * Recibe el frame donde se mostrará, el mensaje que contendrá y el tipo de
     * notificación que es.
     * 
     * Es privado para que no se pueda instanciar la clase, solo usar el método
     * estático para mostrar diálogos. 
     */
    private dlgNotificacion(Frame parent, String mensaje, TipoNotificacion tipo) {
        super(parent, true);
        initComponents();
        /*
        Esto es para que se centre el diálogo y se vea bonito.
        */
        this.mensaje.setText("<html><div style='width: 250px; text-align: center;'>" + mensaje + "</div></html>");
        this.tipoNotificacion.setText(tipo.toString());
        /*
        Según el tipo de notificación, define cuáles botones serán visibles.
        */
        switch(tipo){
            case TipoNotificacion.CONFIRMACIÓN:
                btnAceptar.setVisible(true);
                btnCancelar.setVisible(true);
                break;
            default:
                btnAceptar.setVisible(true);
                btnCancelar.setVisible(false);
        }
        this.setLocationRelativeTo(parent);
    }
    
    /**
     * Método para que sea más fácil generar notificaciones sin necesidad de 
     * construir objetos de la clase cómo tal.
     * @param parent Frame donde se ha de mostrar.
     * @param mensaje Mensaje de la notificación.
     * @param tipo Ya sea un mensaje, un error o una confirmación de usuario.
     */
    public static int mostrarNotificacion(Frame parent, String mensaje, TipoNotificacion tipo){
        dlgNotificacion noti = new dlgNotificacion(parent, mensaje, tipo);
        noti.setVisible(true);
        return noti.opcion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        tipoNotificacion = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 187, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 187, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCancelar.setBackground(new java.awt.Color(163, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAceptar.setBackground(new java.awt.Color(0, 153, 102));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        tipoNotificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipoNotificacion.setText("Tipo de Notificación");

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Mensaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tipoNotificacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tipoNotificacion)
                .addGap(34, 34, 34)
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Es para cerrar el JDialog pero pues ni botón de cerrar tiene.
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

    }//GEN-LAST:event_closeDialog

    /**
     * Botón para cancelar la operación del JDialog.
     * 
     * Guarda la opción y cierra el JDialog.
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        opcion = RET_CANCELAR;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Botón para aceptar la operación del JDialog.
     * 
     * Guarda la opción y cierra el JDialog.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        opcion = RET_ACEPTAR;
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel tipoNotificacion;
    // End of variables declaration//GEN-END:variables

}
